### ISSUE TITLE
Clean/normalize dni method

### ISSUE THREAD

**Issue by finnp** [albertfdp/dni-js#1]
It would be nice if there was a method to normalize a dni like

```
dni.normalize('   12 34 56 7 8-z') //=> '12345678-Z'
```

**Comment by albertfdp** [comment]
Hi @finnp, sorry looks like I missed this, and never had a chance to look at it. 

Gave a try here https://github.com/albertfdp/dni-js/pull/2 do you think that would cover your use case?
